import Head from 'next/head';
import React from 'react';
import styles from '../../../styles/Layout.module.css';

const Layout = ({ children }) => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header className={styles.header}>
				<h1 className={styles.logo}>World rank</h1>
			</header>
			<main className={styles.main}>{children}</main>

			<footer className={styles.footer}>MD MAHADI HASAN @ automatebiz.co.uk</footer>
		</div>
	);
};

export default Layout;
